global_comp_c_flags = ["-std=c23"]

[builder.release]
binaries = [{bin="hello_world"}]

[builder.debug]
comp_flags = ["-DDEBUG"]
binaries = [{bin="hello_world"}]

[binary.hello_world]
type = "executable"
sources = ["main"]